export enum ALGORITHM {
  OBJECT_DETECTION = '0',
  OBJECT_COUNTING = '1',
  IMAGE_CLASSIFICATION = '2',
  POINTER_METER = '3',
  DIGITAL_METER = '4',
}

export enum PROTOCOL {
  WEBUSB = 'webusb',
  SERIAL = 'serial',
}

export enum EVENT {
  NONE = 0,
  CONNECTED = 0x01,
  DISCONNECTED = 0x02,
  LOGGER = 0x04,
  MONITOR = 0x08,
  PREVIEW = 0x10,
  CONFIG_POINTER_START = 0x20,
  CONFIG_POINTER_END = 0x40,
  CONFIG_POINTER_CENTER = 0x80,
  CONFIG_POINTER_CANCEL = 0x100,
  CONFIG_POINTER_DONE = 0x200,
}

export enum DEVICESTATUS {
  UNCONNECTED = 0,
  SERIALCONNECTED = 1,
  ESPCONNECTED = 2,
}
